openapi: 3.0.0
info:
  title: Blog App
  description: Full stack bloging website
  version: 1.0.1
  contact:
    email: dhalisuman001@gmail.com
    url: https://sumandhali.online

servers:
  - url: "{protocol}://localhost:4000/api/{version}"
    description: localhost server
    variables:
      version:
        enum:
          - v1
          - v2
        default: v1
      protocol:
        enum:
          - http
          - https
        default: http

components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT

# Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYzMWQ4YzU3Yzg1MzNkNTk5ZmNlNjg2ZCIsImlhdCI6MTY2MzA5MTUyOCwiZXhwIjoxNjY0ODE5NTI4fQ.XAW1owNSyTl6iwkkX9ZaL7pI4pnalA-8BdwP8zLTPpQ
definitions:
  User:
    type: object
    required:
      - firstname
      - lastname
      - email
      - password
    properties:
      firstname:
        type: string
      lastname:
        type: string
      email:
        type: string
      password:
        type: string

paths:
  /users/register:
    post:
      tags:
        - Users
      summary: register as a new user required files are first name, last name, password and email.
      consumes:
        content:
          application/json:
      parameters:
        - in: body
          name: user
          description: all fields are rquired
          schema:
            $ref: "#/definitions/User"

      reqestBody:
        content:
          application/json:
            schema:
              type: object
              required:
                - firstname
                - lastname
                - email
                - password
              properties:
                firstname:
                  type: string
                  required: true

                lastname:
                  type: string
                  required: true

                email:
                  type: string
                  required: true

                password:
                  type: string
                  required: true

      responses:
        200:
          description: successfully register
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: string
                  User:
                    type: object
                    properties:
                      firstname:
                        type: string
                      lastname:
                        type: string
                      email:
                        type: string
                      password:
                        type: string
        400:
          description: bad request
        500:
          description: internal server error
